### ISSUE TITLE
http_query failed

### ISSUE THREAD

**Issue by tczengming** [DNSPod/dplus-c#3]
http_query always failed, this is the patch:

diff --git a/src/http.c b/src/http.c
index 0b5bbc9..6314236 100644
--- a/src/http.c
+++ b/src/http.c
@@ -66,7 +66,7 @@ static int receive_all(int sockfd, char *buf, size_t length) {
         int ret;
         ret = wait_readable(sockfd, timeout);
         if (ret != 0)
-            return -1;
+            return bytes_received; // www.benew.xyz fix http_query failed

         ret = recv(sockfd, buf + bytes_received, length - bytes_received, 0);
         if (ret > 0) {

**Comment by jfb8856606** [comment]
Thanks for patch.
